// Server-only — never shipped to the client bundle. If this vocabulary were
// part of @smoosh/protocol it would ship in every player's JS, letting anyone
// inspect it and recognize the real prompt during GUESS.
//
// Prompts are generated by combining slots, and every slot word maps to
// something players can actually find in the asset library (animals, parts,
// props, backgrounds — see public/assets/manifest.json). The combinations
// are random on purpose: the absurdity is the game. When the library gains
// new tags, add them to the matching slot here.

// animals + people who can be the star of a scene
const CHARACTERS = [
  'Pug',
  'Sloth',
  'Llama',
  'Alpaca',
  'Goat',
  'Highland Cow',
  'Flamingo',
  'Barn Owl',
  'Snow Owl',
  'Pigeon',
  'Tree Frog',
  'Tomato Frog',
  'Hen',
  'Crab Spider',
  'Rubber Duck',
  'Mannequin',
  'Lumberjack',
  'Plumber',
  'Electrician',
  'Guardian Angel',
  'Toddler',
  'Businessman',
  'Grandma',
  'Marble Statue',
]

// costume pieces from the "parts" category, phrased to follow a character
const OUTFITS = [
  'in a Royal Crown',
  'in Sunglasses',
  'in a Hard Hat',
  'with a Huge Beard',
  'in Rubber Boots',
  'in a Terrible Wig',
  'in a Face Mask',
  'with Angel Wings',
  'in a Necktie',
  'in a Black Hat',
  'in a Fancy Coat',
  'with a Wrist Watch',
]

// verb phrases built around props
const ACTIONS = [
  'Playing Guitar',
  'Singing Into a Microphone',
  'Juggling Bananas',
  'Chainsawing a Birthday Cake',
  'Stealing a Trophy',
  'Pushing a Wheelbarrow Full of Eggs',
  'Directing Traffic With a Cone',
  'Unclogging a Toilet',
  'Hoarding Toilet Paper',
  'Guarding a Mysterious Briefcase',
  'Taking Paparazzi Photos',
  'Licking an Ice Cream Cone',
  'Hugging a Cactus',
  'Grilling Pine Cones',
  'Riding a Giant Rubber Duck',
  'Chopping Firewood',
  'Packing a Suitcase in a Panic',
  'Drinking From a Tiny Cup',
  'Selling Stolen Sponges',
  'Blowing a Horn at Everyone',
  'Carrying a Stack of Bricks',
  'Eating a Whole Fish',
]

// scenes from the "backgrounds" and "nature" categories
const PLACES = [
  'at the Airport',
  'in Court',
  'in the Operating Room',
  'at the Gym',
  'in the Supermarket',
  'in a Hotel Lobby',
  'in a Parking Garage',
  'in Outer Space',
  'in the Desert',
  'in a Classroom',
  'at the Office',
  'in the Bathroom',
  'at the Pool',
  'in the Waiting Room',
  'in an Abandoned Hospital',
  'on a Pirate Galleon',
  'in the Kitchen',
  'at the Bar',
  'on a Train',
  'in a Lecture Hall',
  'at a Campfire',
  'in a Swamp',
  'at a Fancy Restaurant',
  'on a Tropical Island',
  'in a Burning Building',
]

// jobs that pair with a background
const JOBS = [
  'Surgeon',
  'Judge',
  'Receptionist',
  'Lifeguard',
  'Barista',
  'Personal Trainer',
  'Flight Attendant',
  'Teacher',
  'Firefighter',
  'Supermarket Cashier',
  'Airplane Pilot',
  'Hotel Concierge',
]

// what two characters get up to together
const DUO_ACTIONS = [
  'Getting Divorced',
  'Fighting Over the Last Banana',
  'Starting a Rock Band',
  'on an Awkward First Date',
  'Having a Dance-Off',
  'Racing Wheelbarrows',
  'Robbing a Bank',
  'Arguing About a Toilet Roll',
]

// keeps prompts readable in the prompt bar and well under LIE_TEXT_MAX_LEN,
// so a lie in the same style always fits
const MAX_PROMPT_LEN = 60
const POOL_SIZE = 600

type Rng = () => number

const pick = <T,>(list: readonly T[], rng: Rng): T => {
  const value = list[Math.floor(rng() * list.length)]
  if (value === undefined) throw new Error('pick from empty list')
  return value
}

const TEMPLATES: ReadonlyArray<(rng: Rng) => string> = [
  (rng) => `${pick(CHARACTERS, rng)} ${pick(ACTIONS, rng)} ${pick(PLACES, rng)}`,
  (rng) => `${pick(CHARACTERS, rng)} ${pick(OUTFITS, rng)} ${pick(ACTIONS, rng)}`,
  (rng) => `${pick(CHARACTERS, rng)} ${pick(OUTFITS, rng)} ${pick(PLACES, rng)}`,
  (rng) => `${pick(CHARACTERS, rng)} Working as a ${pick(JOBS, rng)}`,
  (rng) => `${pick(CHARACTERS, rng)} ${pick(JOBS, rng)} ${pick(PLACES, rng)}`,
  (rng) => {
    const a = pick(CHARACTERS, rng)
    let b = pick(CHARACTERS, rng)
    while (b === a) b = pick(CHARACTERS, rng)
    return `${a} and ${b} ${pick(DUO_ACTIONS, rng)}`
  },
]

export function generatePromptPool(size: number = POOL_SIZE, rng: Rng = Math.random): string[] {
  const pool = new Set<string>()
  // bounded so a too-small vocabulary can't spin forever
  for (let attempts = 0; pool.size < size && attempts < size * 20; attempts++) {
    const prompt = pick(TEMPLATES, rng)(rng)
    if (prompt.length <= MAX_PROMPT_LEN) pool.add(prompt)
  }
  return [...pool]
}

// generated once per server process; rooms track their own usedPrompts, so
// a long game never repeats a prompt
export const PROMPT_POOL: readonly string[] = generatePromptPool()
