// Server-only — never shipped to the client bundle. If this list were part
// of @smoosh/protocol it would ship in every player's JS, letting anyone
// inspect it and instantly recognize the real prompt during GUESS across
// repeat games. Keep additions in the same "[character] [doing something
// absurd]" tone as the rest of the list.
export const PROMPT_POOL: readonly string[] = [
  'Vampire Bunny Hotel Reception',
  'Disgraced Wizard Applying for Unemployment',
  'Octopus DJ at a Silent Disco',
  'Medieval Knight Doing Taxes',
  'Astronaut Allergic to Space',
  'Pirate Captain of a Rubber Duck Fleet',
  'Grandma Winning an Illegal Street Race',
  'Dinosaur Working the Night Shift at a Diner',
  'Ghost Trying to Return an Overdue Library Book',
  'Robot Learning to Ride a Unicycle',
  'Mermaid Failing a Swimming Lesson',
  'Werewolf at a Full Moon Support Group',
  'Toddler CEO Running a Board Meeting',
  'Sasquatch Getting a Haircut',
  'Cyborg Grandpa Telling War Stories',
  'Elf Union Rep Negotiating Overtime',
  'Zombie Barista Learning Latte Art',
  'Alien Tourist Trying Earth Food for the First Time',
  'Penguin Waiter at a Fancy Restaurant',
  'Dragon Landlord Collecting Rent',
  'Time-Traveling Plumber Fixing a Leak in 1200 AD',
  'Ninja Librarian Shushing an Intruder',
  'Genie Stuck in a Vending Machine',
  'Cat Burglar Who Is Also Literally a Cat',
  'Vampire Dentist Examining a Garlic Bread Sandwich',
  'Superhero Filing an Insurance Claim',
  'Yeti Trying to Blend in at the Office',
  'Fairy Godmother on Strike',
  'Sea Captain Afraid of Water',
  'Skeleton Getting a Massage',
  'Dracula Ordering a Sunbed',
  'Minotaur Lost in an IKEA',
  'Centaur Failing a Driving Test',
  'Cupid Getting Fired for Bad Aim',
  'Leprechaun Doing an Audit',
  'Phoenix Trying to Extinguish Itself',
  'Gnome Landscaper Sabotaging the Lawn',
  'Bigfoot Modeling for a Shoe Ad',
  'Kraken Afraid of Bath Time',
  "Wizard's Apprentice Who Keeps Setting Things on Fire",
  'Unicorn at the DMV',
  'Troll Moderating a Comment Section',
  'Sphinx Running a Trivia Night',
  "Frankenstein's Monster on a First Date",
  'Banshee Trying to Whisper',
  'Gremlin Fixing the WiFi',
  'Headless Horseman Looking for His Helmet',
  'Witch Doctor Reviewing Yelp Complaints',
  'Loch Ness Monster Doing a Photoshoot',
  'Angel Intern Learning the Ropes',
  'Demon Accountant Closing the Books',
  'Chupacabra Raiding a Vending Machine',
  'Goblin King Doing Karaoke',
  'Ogre Attending Etiquette School',
  'Harpy Delivering Mail in a Storm',
  'Mummy Unwrapping Gifts on Christmas',
  'Cursed Pirate Doing Laundry',
  'Basilisk at an Eye Doctor Appointment',
  'Wendigo Trying Vegetarianism',
  'Golem Learning to Dance',
  'Poltergeist Rearranging IKEA Furniture',
  'Shapeshifter Stuck as a Traffic Cone',
  'Valkyrie Chaperoning a School Dance',
  'Cerberus at the Vet, All Three Heads Disagreeing',
  'Hydra Trying to Get a Haircut',
  'Imp Working Customer Service',
  'Jackalope Auditioning for a Nature Documentary',
  "Kelpie Giving Swimming Lessons It Shouldn't",
  'Lich Doing Inventory in the Basement',
  'Manticore Stuck in a Revolving Door',
  'Naga Trying on Pants for the First Time',
  'Oracle Giving Terrible Investment Advice',
  'Pixie Assembling Flat-Pack Furniture',
  'Quetzalcoatl Learning to Parallel Park',
  'Rakshasa Hosting a Cooking Show',
  'Satyr Teaching a Yoga Class',
  'Titan Trying to Fit Through a Doorway',
  'Undine Complaining About Chlorine',
  "Valkyrie's Horse Getting Shoed at the Farrier",
  'Wraith Haunting the Wrong House by Mistake',
  'Yowie Applying Sunscreen for the First Time',
  'Zombie Influencer Filming a Skincare Routine',
  'Abominable Snowman on a Tropical Vacation',
  'Boogeyman Afraid of the Dark',
  'Changeling at Its Own Family Reunion',
  'Djinn Negotiating the Fine Print of a Wish',
  'Ent Getting Stuck in Rush Hour Traffic',
  'Fury Trying Anger Management',
  'Gargoyle Getting Pigeon-Proofed',
  'Hobgoblin Doing Freelance Taxes',
  'Incubus Working the Overnight Shift at a Diner',
  'Jinn Lamp Salesman Who Hates His Job',
]

if (new Set(PROMPT_POOL).size !== PROMPT_POOL.length) {
  throw new Error('PROMPT_POOL contains duplicate entries')
}
